[lookup]
surbl-hashbl = { "0ven.io",
"1drv.ms",
"1kb.link",
"1th.me",
"2ww.me",
"4.fo",
"abre.ai",
"alturl.com",
"api.whatsapp.com",
"arweave.net",
"bit.do",
"bit.ly",
"bitly.ws",
"bom.so",
"buff.ly",
"c4rex.co",
"cdn.discordapp.com",
"cdn.via.com",
"cf-ipfs.com",
"citly.me",
"clcr.me",
"cld.pt",
"cleanuri.com",
"clicktracker.net",
"cloudflare-ipfs.com",
"commondatastorage.googleapis.com",
"crustwebsites.net",
"cutlly.com",
"cutt.ly",
"cutt.us",
"d8hxy.app.goo.gl",
"dik.si",
"drive.google.com",
"dweb.link",
"eblink4.com",
"eblink5.com",
"eu2.contabostorage.com",
"firebasestorage.googleapis.com",
"fleek.cool",
"fleek.ipfs.io",
"flowto.it",
"forms.gle",
"g.bmb.jp",
"gateway.ipfs.io",
"gateway.lighthouse.storage",
"geno.link",
"gg.gg",
"ggle.io",
"goo.gl",
"goo.su",
"gtly.to",
"han.gl",
"hardbin.com",
"hashbltest.surbl.org",
"hashbltest2.surbl.org",
"heyflow.id",
"ht.ly",
"htl.li",
"httpslink.com",
"ibit.ly",
"inx.lv",
"ipfs.eth.aragon.network",
"ipfs.fleek.co",
"ipfs.io",
"iqy.im",
"is.gd",
"itsssl.com",
"ja.cat",
"ja2r7.app.goo.gl",
"jpeg.ly",
"kortlink.dk",
"kutt.it",
"kuza.me",
"l8.nu",
"li-ne.me",
"lihi.cc",
"lin.ee",
"line.me",
"link-shortener.net",
"link.nn.ru",
"linkmn.gr",
"linktr.ee",
"ln.run",
"lnk.sk",
"lnkd.in",
"lnkiy.in",
"m17.ca",
"m1s.it",
"m6z.cn",
"me-qr.com",
"mpago.la",
"mq.mbd.baidu.com",
"mq4.ru",
"mub.me",
"my.forms.app",
"n9.cl",
"nftstorage.link",
"objects-us-east-1.dream.io",
"ow.ly",
"p.st",
"pastebin.com",
"peg3z.app.goo.gl",
"peyg.ir",
"piplynow.com",
"ppt.cc",
"ptpn4.id",
"pxlme.me",
"qrco.de",
"qrs.ly",
"r10.to",
"rb.gy",
"rcw3r.app.goo.gl",
"rebrand.ly",
"reurl.cc",
"rotf.lol",
"rplg.co",
"s.free.fr",
"s.id",
"s.lu",
"s3.amazonaws.com",
"s3.us-west-1.amazonaws.com",
"sfo3.digitaloceanspaces.com",
"sgp1.digitaloceanspaces.com",
"shln.me",
"short-me.me",
"short.gy",
"shorter.gg",
"shortly.at",
"shorturl.ac",
"shorturl.asia",
"shorturl.at",
"shrinke.me",
"shrtco.de",
"siasky.net",
"sites.google.com",
"snip.ly",
"ssur.cc",
"storage.cloud.google.com",
"storage.googleapis.com",
"storageapi.fleek.co",
"substack.com",
"surl.li",
"swll.to",
"syd1.digitaloceanspaces.com",
"t.co",
"t.ly",
"t.me",
"telegra.ph",
"tiny.cc",
"tiny.one",
"tinylink.in",
"tinyurl.com",
"tls.tc",
"tny.im",
"to.sv",
"trimmer.to",
"twtr.to",
"tyl.ke",
"u.to",
"uclck.ru",
"url-s.xyz",
"url.com",
"url.zip",
"urlcc.cc",
"urly.it",
"urlz.fr",
"urlzs.com",
"usc1.contabostorage.com",
"vk.cc",
"vk.sv",
"vo.la",
"wa.link",
"wa.me",
"www.bit.do",
"www.goo.su",
"x.gd",
"xek99.app.goo.gl",
"xurl.es",
"yhv6e.app.goo.gl",
"zpr.io"}
