[[spam-filter.rule]]
enable = true
scope = "email"
priority = 60
condition = [ { if = "contains(['to', 'cc', 'bcc'], location) && contains_ignore_case(name, recipient)", then = "'TO_DN_RECIPIENTS'" },
			  { else = false } ]

[[spam-filter.rule]]
enable = true
scope = "email"
priority = 60
condition = [ { if = "contains(['to', 'cc', 'bcc'], location) && local == 'info' && from.local == 'info' && $X_HDR_LIST_UNSUBSCRIBE", then = "'INFO_TO_INFO_LU'" },
			  { else = false } ]

[[spam-filter.rule]]
enable = true
scope = "email"
priority = 60
condition = [ { if = "contains(['to', 'cc', 'bcc'], location) && contains(local, '+')", then = "'TAGGED_RCPT'" },
			  { else = false } ]

