[spam-filter.rule.STWT_SUBJ_BOUNCE_WORDS]
enable = true
scope = "any"
priority = 20
condition = [ { if = "(contains(subject, 'delivery') && 
            (contains(subject, 'failed') || 
             contains(subject, 'report') || 
             contains(subject, 'status') || 
             contains(subject, 'warning'))) ||
         (contains(subject, 'failure') && 
            (contains(subject, 'delivery') || 
             contains(subject, 'notice') || 
             contains(subject, 'mail') )) ||
         (contains(subject, 'delivered') &&
            (contains(subject, 'couldn\\'t be') || 
             contains(subject, 'could not be') || 
             contains(subject, 'hasn\\'t been') || 
             contains(subject, 'has not been'))) ||
         contains(subject, 'returned mail') ||
         contains(subject, 'undeliverable') || 
         contains(subject, 'undelivered')", then = "'SUBJ_BOUNCE_WORDS'" },
			   { else = false } ]

[spam-filter.rule.STWT_BOUNCE_SUBJECT]
enable = true
scope = "any"
priority = 21
condition = [ { if = "!$BOUNCE && is_empty(env_from) && $SUBJ_BOUNCE_WORDS && (contains(from.local, 'postmaster') || contains(from.local, 'mailer-daemon'))", then = "'BOUNCE'" },
			   { else = false } ]

[spam-filter.rule.STWT_SUBJECT_HAS_SYMBOLS]
enable = true
scope = "any"
priority = 22
condition = [ { if = "ends_with(trim(subject), '!')", then = "'SUBJECT_ENDS_EXCLAIM'" },
              { if = "ends_with(trim(subject), '?')", then = "'SUBJECT_ENDS_QUESTION'" },
              { if = "contains(subject, '!')", then = "'SUBJECT_HAS_EXCLAIM'" },
              { if = "contains(subject, '?')", then = "'SUBJECT_HAS_QUESTION'" },
			  { else = false } ]

[spam-filter.rule.STWT_LONG_SUBJ]
enable = true
scope = "any"
priority = 23
condition = [ { if = "len(subject) > 200", then = "'LONG_SUBJ'" },
			  { else = false } ]

[spam-filter.rule.STWT_FAKE_REPLY]
enable = true
scope = "any"
priority = 24
condition = [ { if = "contains_ignore_case(['re', 'aw', 'antw', 'sv'], split_once(subject, ':')[0]) && !$X_HDR_IN_REPLY_TO && !$X_HDR_REFERENCES", then = "'FAKE_REPLY'" },
			  { else = false } ]

